routes/web.php
<?php

use App\Http\Controllers\Auth\LoginController;
use App\Http\Controllers\AuthController;
use App\Http\Controllers\ChatMessageController;
use App\Http\Controllers\ClientController;
use App\Http\Controllers\contactController;
use App\Http\Controllers\DashboardController;
use App\Http\Controllers\ReportController;
use App\Http\Controllers\TemplateController;
use App\Http\Controllers\WhatsAppController;
use GuzzleHttp\Client;
use Illuminate\Support\Facades\Auth;
use Illuminate\Support\Facades\Http;
use Illuminate\Support\Facades\Route;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', function () {
    return view('app');
});

Auth::routes(['register'=>false]);
Route::get('logout',[LoginController::class,'logout'])->name('exit');

Route::group(['prefix'=>'admin' , 'as' => 'admin.', 'middleware' => ['auth','admin']],
function(){
    Route::get('/dashboard',[DashboardController::class,'index']);
});

Route::group(['prefix' => 'client', 'as' => 'client.', 'middleware' => ['auth']], function ()
	{
		Route::get('/dashboard', [ClientController::class,'index'])->name('ClientDashboard');
        Route::get('settings/',[ClientController::class,'settings'])->name('settings');
        Route::post('/update-password',[ClientController::class,'changePassword'])->name('update.password');
        Route::post('update-information',[ClientController::class,'update'])->name('update.information');
        Route::post('update_email',[ClientController::class,'changeEmail'])->name('update.email');
        Route::post('update-avatar',[ClientController::class,'updateAvatar'])->name('update.avatar');
        Route::get('avatar',[ClientController::class,'avatar'])->name('avatar');

});

Route::match(['get','post'],'import-contacts',[contactController::class,'import_contacts']);

Route::prefix('whatsapp')->name('whatsapp.')->group(function () {
    Route::get('/quick-send', [WhatsappController::class,'send_text'])->name('quick_send');
    Route::post('/bulk-send', [WhatsappController::class,'send_text'])->name('bulk');
    Route::post('sendmessage',[ChatMessageController::class,'sendMessage'])->name('message');
    Route::get('chat',[ChatMessageController::class,'fetch_messages'])->name('chat');
    Route::get('template_message',[ChatMessageController::class,'template_message'])->name('template_message');
    Route::get('media-send',[ChatMessageController::class,'media'])->name('media');
    Route::post('media-send',[ChatMessageController::class,'sendMediaMessage'])->name('media.send');
    Route::post('upload_file',[ChatMessageController::class,'uploadFile'])->name('upload.file');
    Route::get('campaign',[ChatMessageController::class,'campaignBuilder'])->name('campaign');
    Route::post('save_campaign',[ChatMessageController::class,'storeCampaign'])->name('save.campaign');
});

Route::prefix('template')->name('templates.')->group(function () {
    Route::get('/list', [TemplateController::class,'index'])->name('list');
    Route::get('/new', [TemplateController::class,'create'])->name('create');
    Route::post('save',[TemplateController::class,'save'])->name('save');
});



Route::prefix('reports')->name('reports.')->group(function () {
    Route::get('/all_messages', [ReportController::class,'index'])->name('messages');
    Route::get('/outbound_messages', [ReportController::class,'outbound_msgs'])->name('outbound');
    Route::get('/inbound_messages', [ReportController::class,'inbound_msgs'])->name('inbound');
    Route::post('/{id}/view', [ReportController::class,'view_message']);
});

Route::prefix('contacts')->name('contacts.')->group(function () {
    Route::get('/groups',[contactController::class,'show_groups'])->name('group.list');
    Route::get('/create_group',[contactController::class,'create'])->name('create');
    Route::post('/create_group', [contactController::class,'create_contact_group'])->name('create.group');
    Route::get('/view_group/{contact}', [contactController::class,'show'])->name('view');
    Route::get('show_contacts',[contactController::class,'get_contacts'])->name('list');
    Route::get('contact/{id}',[contactController::class,'create_contact'])->name('create.contact');
    Route::post('contact',[contactController::class,'create_contact'])->name('create.contact');
    Route::post('single_contact',[contactController::class,'single_contact'])->name('single.contact');
    Route::match(['get','post'],'{contact}/import-contacts',[contactController::class,'import_contacts'])->name('import');
    Route::get('{contact}/import', [contactController::class,'import'])->name('group.import');
    Route::post('{contact}/store_import', [contactController::class,'store_import'])->name('save.import');
});


Route::get('wap-api',[WhatsAppController::class,'auth']);
Route::get('chat-box',[WhatsAppController::class,'authCheck']); //call on open app\


Route::get('sample_file',function(){
    return response()->download(storage_path('app/contacts.csv'));
})->name('sample.file');

Route::post('/messages',[ChatMessageController::class,'save_message']);

app/Models/ContactGroup.php
<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Database\Eloquent\Model;
use Illuminate\Database\Eloquent\Relations\BelongsTo;
use Illuminate\Database\Eloquent\Relations\HasMany;

class ContactGroup extends Model
{
    use HasFactory;

    protected $guarded = ['id'];

    public function contacts(): HasMany
    {
        return $this->hasMany(Contact::class,'group_id');
    }

    public function client(): BelongsTo
    {
        return $this->belongsTo(Client::class,'client_id');
    }

    public function updateCache($key = null)
    {
        $index = [
            'SubscribersCount' => function ($group) {
                return $group->subscribersCount();
            },
        ];

        // retrieve cached data
        $cache = json_decode($this->cache, true);
        if (is_null($cache)) {
            $cache = [];
        }

        if (is_null($key)) {
            // update all cache
            foreach ($index as $key => $callback) {
                $cache[$key] = $callback($this);
                if ($key == 'SubscribersCount') {
                    // SubscriberCount cache must always be updated as its value will be used for the others
                    $this->cache = json_encode($cache);
                    $this->save();
                }
            }
        } else {
            // update specific key
            $callback    = $index[$key];
            $cache[$key] = $callback($this);
        }

        // write back to the DB
        $this->cache = json_encode($cache);
        $this->save();

    }

    public function subscribersCount($cache = false): int
    {
        if($cache){
            return $this->readCache('SubscribersCount',0);
        }
        return $this->contacts()->count();
    }

    public function readCache($key, $default = null){
        $cache = json_decode($this->cache,true);
        if(is_null($cache)){
            return $default;
        }
        if(array_key_exists($key,$cache)){
            if(is_null($cache[$key])){
                return $default;
            }else {
                return $cache[$key];
            }
        }else{
            return $default;
        }
    }

    public function getRouteKeyName(): string
    {
        return 'id';
    }
}

resources/views/contactGroups/grp_contact.blade.php
<div class="card">
    <!--begin::Card header-->
    <div class="card-header border-0 pt-6">
        <!--begin::Card title-->
        <div class="card-title">
            <!--begin::Search-->
            <div class="d-flex align-items-center position-relative my-1">
                <!--begin::Svg Icon | path: icons/duotune/general/gen021.svg-->
                <span class="svg-icon svg-icon-1 position-absolute ms-6">
                    <i class="bi bi-search"></i>
                </span>
                <!--end::Svg Icon-->
                <input type="text" data-kt-user-table-filter="search" class="form-control form-control-solid w-250px ps-14" placeholder="Search user" />
            </div>
            <!--end::Search-->
        </div>
        <!--begin::Card title-->
        <!--begin::Card toolbar-->
        <div class="card-toolbar">
            <!--begin::Toolbar-->
            <div class="d-flex justify-content-end" data-kt-user-table-toolbar="base">
                <a type="button" class="btn btn-light-primary me-3" href="{{route('contacts.group.import',['contact'=>$contact->id])}}" >
                    <span class="svg-icon svg-icon-2">
                        <i class="bi bi-input-cursor"></i>
                    </span>  Import</a>
                <button type="button" class="btn btn-primary" data-bs-toggle="modal" data-bs-target="#kt_modal_add_user">
                    <!--begin::Svg Icon | path: icons/duotune/arrows/arr075.svg-->
                    <span class="svg-icon svg-icon-2">
                        <svg xmlns="http://www.w3.org/2000/svg" width="24" height="24" viewBox="0 0 24 24" fill="none">
                            <rect opacity="0.5" x="11.364" y="20.364" width="16" height="2" rx="1" transform="rotate(-90 11.364 20.364)" fill="black" />
                            <rect x="4.36396" y="11.364" width="16" height="2" rx="1" fill="black" />
                        </svg>
                    </span>
                    Add User</button>
                <!--end::Add user-->
            </div>
            <!--end::Toolbar-->
            <!--begin::Group actions-->
            <div class="d-flex justify-content-end align-items-center d-none" data-kt-user-table-toolbar="selected">
                <div class="fw-bolder me-5">
                    <span class="me-2" data-kt-user-table-select="selected_count"></span>Selected</div>
                <button type="button" class="btn btn-danger" data-kt-user-table-select="delete_selected">Delete Selected</button>
            </div>
            <!--end::Modal - New Card-->
            <!--begin::Modal - Add task-->
            <div class="modal fade" id="kt_modal_add_user" tabindex="-1" aria-hidden="true">
                <!--begin::Modal dialog-->
                <div class="modal-dialog modal-dialog-centered mw-650px">
                    <!--begin::Modal content-->
                    <div class="modal-content">
                        <!--begin::Modal header-->
                        <div class="modal-header" id="kt_modal_add_user_header">
                            <!--begin::Modal title-->
                            <h2 class="fw-bolder">Add User</h2>
                            <!--end::Modal title-->
                            <!--begin::Close-->
                            <div class="btn btn-icon btn-sm btn-active-icon-primary" data-kt-users-modal-action="close">
                                <!--begin::Svg Icon | path: icons/duotune/arrows/arr061.svg-->
                                <span class="svg-icon svg-icon-1">
																	<svg xmlns="http://www.w3.org/2000/svg" width="24" height="24" viewBox="0 0 24 24" fill="none">
																		<rect opacity="0.5" x="6" y="17.3137" width="16" height="2" rx="1" transform="rotate(-45 6 17.3137)" fill="black" />
																		<rect x="7.41422" y="6" width="16" height="2" rx="1" transform="rotate(45 7.41422 6)" fill="black" />
																	</svg>
																</span>
                                <!--end::Svg Icon-->
                            </div>
                            <!--end::Close-->
                        </div>
                        <!--end::Modal header-->
                        <!--begin::Modal body-->
                        <div class="modal-body scroll-y mx-5 mx-xl-15 my-7">
                            <!--begin::Form-->
                            <form id="kt_modal_add_user_form" class="form" >
                                <!--begin::Scroll-->
                                <div class="d-flex flex-column scroll-y me-n7 pe-7" id="kt_modal_add_user_scroll" data-kt-scroll="true"
                                     data-kt-scroll-activate="{default: false, lg: true}"
                                     data-kt-scroll-max-height="auto"
                                     data-kt-scroll-dependencies="#kt_modal_add_user_header"
                                     data-kt-scroll-wrappers="#kt_modal_add_user_scroll"
                                     data-kt-scroll-offset="300px">
                                    <!--begin::Input group-->
                                    <input hidden name="group_id" value="">
                                    <div class="fv-row mb-7">
                                        <!--begin::Label-->
                                        <label class="required fw-bold fs-6 mb-2">First Name</label>
                                        <!--end::Label-->
                                        <!--begin::Input-->
                                        <input type="text" name="first_name" id="contact_name" class="form-control form-control-solid mb-3 mb-lg-0" placeholder="First name" value="" />
                                        <!--end::Input-->
                                    </div>
                                    <div class="fv-row mb-7">
                                        <!--begin::Label-->
                                        <label class="required fw-bold fs-6 mb-2">Last Name</label>
                                        <!--end::Label-->
                                        <!--begin::Input-->
                                        <input type="text" name="last_name" id="last_name" class="form-control form-control-solid mb-3 mb-lg-0" placeholder="Last name" value="" />
                                        <!--end::Input-->
                                    </div>
                                    <!--end::Input group-->
                                    <!--begin::Input group-->
                                    <div class="fv-row mb-7">
                                        <!--begin::Label-->
                                        <label class="required fw-bold fs-6 mb-2">Phone Number</label>
                                        <!--end::Label-->
                                        <!--begin::Input-->
                                        <input type="number" name="contact_phone" id="contact_phone" class="form-control form-control-solid mb-3 mb-lg-0" placeholder="254##xxxx" value="" />
                                        <!--end::Input-->
                                    </div>
                                    <!--end::Input group-->

                                </div>
                                <!--end::Scroll-->
                                <!--begin::Actions-->
                                <div class="text-center pt-15">
                                    <button type="reset" class="btn btn-light me-3" data-kt-users-modal-action="cancel">Discard</button>
                                    <button type="submit" class="btn btn-primary" data-kt-users-modal-action="submit">
                                        <span class="indicator-label">Submit</span>
                                        <span class="indicator-progress">Please wait...
                                            <span class="spinner-border spinner-border-sm align-middle ms-2"></span>
                                        </span>
                                    </button>
                                </div>
                                <!--end::Actions-->
                            </form>
                            <!--end::Form-->
                        </div>
                        <!--end::Modal body-->
                    </div>
                    <!--end::Modal content-->
                </div>
                <!--end::Modal dialog-->
            </div>
            <!--end::Modal - Add task-->
        </div>
        <!--end::Card toolbar-->
    </div>
    <!--end::Card header-->
    <!--begin::Card body-->
    <div class="card-body pt-0">
        <!--begin::Table-->
        <table class="table align-middle table-row-dashed fs-6 gy-5" id="kt_table_users">
            <!--begin::Table head-->
            <thead>
            <!--begin::Table row-->
            <tr class="text-start text-muted fw-bolder fs-7 text-uppercase gs-0">
                <th class="w-10px pe-2">
                    <div class="form-check form-check-sm form-check-custom form-check-solid me-3">
                        <input class="form-check-input" type="checkbox" data-kt-check="true"
                               data-kt-check-target="#kt_table_users .form-check-input" value="1" />
                    </div>
                </th>
                <th class="min-w-125px">Name</th>
                <th class="min-w-125px">Phone Number</th>
                <th class="min-w-125px">Created At</th>
                <th class="text-end min-w-100px">Actions</th>
            </tr>
            <!--end::Table row-->
            </thead>
            <!--end::Table head-->
            <!--begin::Table body-->
            <tbody class="text-gray-600 fw-bold">

            @forelse($contacts as $contact)
                <!--begin::Table row-->
                <tr>
                    <!--begin::Checkbox-->
                    <td>
                        <div class="form-check form-check-sm form-check-custom form-check-solid">
                            <input class="form-check-input" type="checkbox" value="1" />
                        </div>
                    </td>
                    <td>{{$contact->first_name}}  {{$contact->last_name}}</td>
                    <td>
                        <div class="badge badge-light fw-bolder">{{$contact->number}}</div>
                    </td>
                    <td>{{$contact->created_at->diffForHumans()}}</td>
                    <!--begin::Action=-->
                    <td class="text-end">
                        <div class="d-flex justify-content-end flex-shrink-0">
                            <a href="javascript:void(0)" id="view-msg" rel="{{$contact->id}}" class="btn btn-icon btn-bg-light btn-active-color-primary btn-sm me-1">
                                <span class="svg-icon svg-icon-3"><i class="bi bi-file fs-3"></i> </span>
                            </a>
                        </div>
                        <!--end::Menu-->
                    </td>
                    <!--end::Action=-->
                </tr>
                <!--end::Table row-->
            @empty
                <!--begin::Table body-->
            <tbody class="fw-bold text-gray-600"></tbody>
            <!--end::Table body-->
            @endforelse
            </tbody>
            <!--end::Table body-->
        </table>
        <!--end::Table-->
    </div>
    <!--end::Card body-->
</div>

resources/views/contactGroups/grp_message.blade.php
<div id="kt_account_profile_details" class="collapse show">
    <!--begin::Form-->
    <form id="" class="form" method="POST" action="{{route('whatsapp.bulk')}}">@csrf
    <!--begin::Card body-->
        <div class="card-body border-top p-9">

            <!--begin::Input group-->
            <div class="row mb-6">
                <label class="col-lg-4 col-form-label fw-bold fs-6">Message</label>
                <div class="col-lg-8 fv-row">
                     <textarea type="text" name="message"  class="form-control  form-control-solid"
                               placeholder="">
                      </textarea>
                </div>
            </div>
        </div>
        <div class="card-footer d-flex justify-content-end py-6 px-9">
            <button type="reset" class="btn btn-light btn-active-light-primary me-2">Discard</button>
            <button type="submit" class="btn btn-primary" id="">Send Message</button>
        </div>
    </form>
</div>

resources/views/contactGroups/import.blade.php
@extends('layouts.index')
@section('content')
    <!--begin::Post-->
    <div class="post d-flex flex-column-fluid" id="kt_post">
        <!--begin::Container-->
        <div id="kt_content_container" class="container-xxl">
            <!--begin::Basic info-->
            <div class="card mb-5 mb-xl-10">
                <!--begin::Card header-->
                <div class="card-header border-0 cursor-pointer" role="button" data-bs-toggle="collapse"
                     data-bs-target="#kt_account_profile_details" aria-expanded="true"
                     aria-controls="kt_account_profile_details">
                    <!--begin::Card title-->
                    <div class="card-title m-0">
                        <h3 class="fw-bolder m-0">Import Contacts</h3>
                    </div>
                    <!--end::Card title-->
                </div>
                <!--begin::Card header-->
                <!--begin::Content-->
                <div id="kt_account_profile_details" class="collapse show">
                    <!--begin::Form-->

                    <form action="{{route('contacts.import',$contact->id)}}" method="POST" class="form" enctype="multipart/form-data" >@csrf
                    <!--begin::Modal body-->
                        <div class=" pt-10 pb-15 px-lg-17">
                            <div class="form-group">
                                <p class="text-uppercase">Sample File</p>
                                <a href="{{route('sample.file')}}" class="btn btn-primary mb-10">
                                    <i class="feather icon-file-text"></i> Download Sample File
                                </a>

                            </div>
                            <!--begin::Input group-->
                            <div class="form-group">
                                <!--begin::Dropzone-->
                                <input type="file" class="btn btn-sm btn-primary me-2" name="import_file" placeholder="Attach files">
                                <!--end::Dropzone-->
                            </div>
                            <span class="form-text fs-6 text-muted">Max file size is 2MB per file.</span>
                            @error('import_file')
                            <div class="text-danger">
                                {{ $message }}
                            </div>
                            @enderror
                            <div class="card-footer d-flex justify-content-end py-6 px-9">
                                <button type="submit" class="btn btn-primary" id="">Upload Contacts</button>
                            </div>
                        </div>
                        <!--end::Modal body-->
                    </form>
                    <!--end::Form-->
                </div>
                <!--end::Content-->
            </div>
            <!--end::Basic info-->
        </div>
    </div>
@endsection
@push('scripts')
    <script>
        const e = "#upload_dropzone",
            t = document.querySelector(e);
        var n = t.querySelector(".dropzone-item");
        n.id = "";
        var a = n.parentNode.innerHTML;
        n.parentNode.removeChild(n);
        var dropzone =  new Dropzone(e, {
            parallelUploads: 3,
            previewTemplate: a,
            maxFilesize: 5,
            autoProcessQueue: !1,
            autoQueue: !1,
            acceptedFiles: ".csv",
            previewsContainer: e + " .dropzone-items",
            clickable: e + " .dropzone-select",
        });
        dropzone.on("addedfile", function (n) {
            (n.previewElement.querySelector(e + " .dropzone-start").onclick = function () {
                const e = n.previewElement.querySelector(".progress-bar");
                e.style.opacity = "1";
                var t = 1,
                    a = setInterval(function () {
                        t >= 100 ? (dropzone.emit("success", n), dropzone.emit("complete", n),
                            clearInterval(a)) : (t++, (e.style.width = t + "%"));
                    }, 20);
            }),
                t.querySelectorAll(".dropzone-item").forEach((e) => {
                    e.style.display = "";
                }),
                (t.querySelector(".dropzone-upload").style.display = "inline-block"),
                (t.querySelector(".dropzone-remove-all").style.display = "inline-block");
        })
        dropzone.on("complete", function (e) {
            const n = t.querySelectorAll(".dz-complete");
            //upload with ajax
            setTimeout(function () {
                n.forEach((e) => {
                    (e.querySelector(".progress-bar").style.opacity = "0"), (e.querySelector(".progress").style.opacity = "0"), (e.querySelector(".dropzone-start").style.opacity = "0");
                });
            }, 300);

            dropzone.uploadFiles = function (files) {
                var self = this;
                for(var i= 0;  i <files.length; i++){
                    var file = files[i];

                }
            }
        })
        t.querySelector(".dropzone-upload").addEventListener("click", function () {
            dropzone.files.forEach((e) => {
                const t = e.previewElement.querySelector(".progress-bar");
                t.style.opacity = "1";
                var n = 1,
                    a = setInterval(function () {
                        n >= 100 ? (dropzone.emit("success", e), dropzone.emit("complete", e), clearInterval(a)) : (n++, (t.style.width = n + "%"));
                    }, 20);
            });
        }),
            t.querySelector(".dropzone-remove-all").addEventListener("click", function () {
                Swal.fire({
                    text: "Are you sure you would like to remove all files?",
                    icon: "warning",
                    showCancelButton: !0,
                    buttonsStyling: !1,
                    confirmButtonText: "Yes, remove it!",
                    cancelButtonText: "No, return",
                    customClass: { confirmButton: "btn btn-primary", cancelButton: "btn btn-active-light" },
                }).then(function (e) {
                    e.value
                        ? ((t.querySelector(".dropzone-upload").style.display = "none"),
                            (t.querySelector(".dropzone-remove-all").style.display = "none") ,
                            dropzone.removeAllFiles(!0))
                        : "cancel" === e.dismiss &&
                        Swal.fire({ text: "Your files was not removed!.",
                            icon: "error", buttonsStyling: !1,
                            confirmButtonText: "Ok, got it!",
                            customClass: { confirmButton: "btn btn-primary" } });
                });
            }),
            dropzone.on("queuecomplete", function (e) {
                t.querySelectorAll(".dropzone-upload").forEach((e) => {
                    e.style.display = "none";
                });
            })
        dropzone.on("removedfile", function (e) {
            dropzone.files.length < 1 && ((t.querySelector(".dropzone-upload").style.display = "none") (t.querySelector(".dropzone-remove-all").style.display = "none"));
        });

    </script>
@endpush

resources/views/contactGroups/view.blade.php
@extends('layouts.index')
@section('content')
    <!--begin::Post-->
    <div class="content d-flex flex-column flex-column-fluid" id="kt_content">
            <div id="kt_toolbar_container" class="container-fluid  flex-stack">
                <div class="card ">
                    <div class="card-header card-header-stretch">
                        <h3 class="card-title">Group Details</h3>
                        <div class="card-toolbar">
                            <ul class="nav nav-tabs nav-line-tabs nav-stretch fs-6 border-0">
                                <li class="nav-item">
                                    <a class="nav-link active" data-bs-toggle="tab" href="#kt_tab_pane_7">Contacts</a>
                                </li>
                                <li class="nav-item">
                                    <a class="nav-link" data-bs-toggle="tab" href="#kt_tab_pane_8">Message</a>
                                </li>
                            </ul>
                        </div>
                    </div>
                    <div class="card-body">
                        <div class="tab-content" id="myTabContent">
                            <div class="tab-pane fade show active" id="kt_tab_pane_7" role="tabpanel">
                               @include('contactGroups.grp_contact')
                            </div>

                            <div class="tab-pane fade" id="kt_tab_pane_8" role="tabpanel">
                                @include('contactGroups.grp_message')
                            </div>
                        </div>
                    </div>
                </div>
            </div>
            <!--end::Container-->
    </div>
    <!--end::Post-->
@endsection