routes/web.php
<?php

use App\Http\Controllers\Auth\LoginController;
use App\Http\Controllers\AuthController;
use App\Http\Controllers\ChatMessageController;
use App\Http\Controllers\ClientController;
use App\Http\Controllers\contactController;
use App\Http\Controllers\DashboardController;
use App\Http\Controllers\ReportController;
use App\Http\Controllers\TemplateController;
use App\Http\Controllers\WhatsAppController;
use GuzzleHttp\Client;
use Illuminate\Support\Facades\Auth;
use Illuminate\Support\Facades\Http;
use Illuminate\Support\Facades\Route;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', function () {
    return view('app');
});

Auth::routes(['register'=>false]);
Route::get('logout',[LoginController::class,'logout'])->name('exit');

Route::group(['prefix'=>'admin' , 'as' => 'admin.', 'middleware' => ['auth','admin']],
function(){
    Route::get('/dashboard',[DashboardController::class,'index']);
});

Route::group(['prefix' => 'client', 'as' => 'client.', 'middleware' => ['auth']], function ()
	{
		Route::get('/dashboard', [ClientController::class,'index'])->name('ClientDashboard');
        Route::get('settings/',[ClientController::class,'settings'])->name('settings');
        Route::post('/update-password',[ClientController::class,'changePassword'])->name('update.password');
        Route::post('update-information',[ClientController::class,'update'])->name('update.information');
        Route::post('update_email',[ClientController::class,'changeEmail'])->name('update.email');
        Route::post('update-avatar',[ClientController::class,'updateAvatar'])->name('update.avatar');
        Route::get('avatar',[ClientController::class,'avatar'])->name('avatar');

});

Route::match(['get','post'],'import-contacts',[contactController::class,'import_contacts']);

Route::prefix('whatsapp')->name('whatsapp.')->group(function () {
    Route::get('/quick-send', [WhatsappController::class,'send_text'])->name('quick_send');
    Route::post('/bulk-send', [WhatsappController::class,'send_text'])->name('bulk');
    Route::post('sendmessage',[ChatMessageController::class,'sendMessage'])->name('message');
    Route::get('chat',[ChatMessageController::class,'fetch_messages'])->name('chat');
    Route::get('template_message',[ChatMessageController::class,'template_message'])->name('template_message');
    Route::get('media-send',[ChatMessageController::class,'media'])->name('media');
    Route::post('media-send',[ChatMessageController::class,'sendMediaMessage'])->name('media.send');
    Route::post('upload_file',[ChatMessageController::class,'uploadFile'])->name('upload.file');
    Route::get('campaign',[ChatMessageController::class,'campaignBuilder'])->name('campaign');
    Route::post('save_campaign',[ChatMessageController::class,'storeCampaign'])->name('save.campaign');
});

Route::prefix('template')->name('templates.')->group(function () {
    Route::get('/list', [TemplateController::class,'index'])->name('list');
    Route::get('/new', [TemplateController::class,'create'])->name('create');
    Route::post('save',[TemplateController::class,'save'])->name('save');
});



Route::prefix('reports')->name('reports.')->group(function () {
    Route::get('/all_messages', [ReportController::class,'index'])->name('messages');
    Route::get('/outbound_messages', [ReportController::class,'outbound_msgs'])->name('outbound');
    Route::get('/inbound_messages', [ReportController::class,'inbound_msgs'])->name('inbound');
    Route::post('/{id}/view', [ReportController::class,'view_message']);
});

Route::prefix('contacts')->name('contacts.')->group(function () {
    Route::get('/groups',[contactController::class,'show_groups'])->name('group.list');
    Route::get('/create_group',[contactController::class,'create'])->name('create');
    Route::post('/create_group', [contactController::class,'create_contact_group'])->name('create.group');
    Route::get('/view_group/{contact}', [contactController::class,'show'])->name('view');
    Route::get('show_contacts',[contactController::class,'get_contacts'])->name('list');
    Route::get('contact/{id}',[contactController::class,'create_contact'])->name('create.contact');
    Route::post('contact',[contactController::class,'create_contact'])->name('create.contact');
    Route::post('single_contact',[contactController::class,'single_contact'])->name('single.contact');
    Route::match(['get','post'],'{contact}/import-contacts',[contactController::class,'import_contacts'])->name('import');
    Route::get('{contact}/import', [contactController::class,'import'])->name('group.import');
    Route::post('{contact}/store_import', [contactController::class,'store_import'])->name('save.import');
});


Route::get('wap-api',[WhatsAppController::class,'auth']);
Route::get('chat-box',[WhatsAppController::class,'authCheck']); //call on open app\


Route::get('sample_file',function(){
    return response()->download(storage_path('app/contacts.csv'));
})->name('sample.file');

Route::post('/messages',[ChatMessageController::class,'save_message']);

resources/views/layouts/footer.blade.php
<!--begin::Footer-->
<div class="footer py-4 d-flex flex-lg-column" id="kt_footer">
    <!--begin::Container-->
    <div class="container-fluid d-flex flex-column flex-md-row align-items-center justify-content-between">
        <!--begin::Copyright-->
        <div class="text-dark order-2 order-md-1">
            <span class="text-muted fw-bold me-1">2021©</span>
            <a href="#" target="_blank" class="text-gray-800 text-hover-primary">Lixnet</a>
        </div>
        <!--end::Copyright-->
        <!--begin::Menu-->
        <ul class="menu menu-gray-600 menu-hover-primary fw-bold order-1">
            <li class="menu-item">
                <a href="https://lixnet.net/" target="_blank" class="menu-link px-2">About</a>
            </li>
            <li class="menu-item">
                <a href="https://lixnet.net/support" target="_blank" class="menu-link px-2">Support</a>
            </li>
        </ul>
        <!--end::Menu-->
    </div>
    <!--end::Container-->
</div>
<!--end::Footer-->

resources/views/layouts/header.blade.php
<!--begin::Header-->
<div id="kt_header" style="" class="header align-items-stretch">
    <!--begin::Container-->
    <div class="container-fluid d-flex align-items-stretch justify-content-between">
        <!--begin::Aside mobile toggle-->
        <div class="d-flex align-items-center d-lg-none ms-n3 me-1" title="Show aside menu">
            <div class="btn btn-icon btn-active-color-white" id="kt_aside_mobile_toggle">
                <i class="bi bi-list fs-1"></i>
            </div>
        </div>
        <!--end::Aside mobile toggle-->
        <!--begin::Mobile logo-->
        <div class="d-flex align-items-center flex-grow-1 flex-lg-grow-0">
            <a href="{{url("/")}}" class="d-lg-none">
                <img alt="Logo" src="{{asset("assets/media/logos/logo-demo13-compact.svg")}}" class="h-25px" />
            </a>
        </div>
        <!--end::Mobile logo-->
        <!--begin::Wrapper-->
        <div class="d-flex align-items-stretch justify-content-between flex-lg-grow-1">
            <!--begin::Navbar-->
            <div class="d-flex align-items-stretch" id="kt_header_nav">
                <!--begin::Menu wrapper-->
                <div class="header-menu align-items-stretch" data-kt-drawer="true" data-kt-drawer-name="header-menu" data-kt-drawer-activate="{default: true, lg: false}" data-kt-drawer-overlay="true" data-kt-drawer-width="{default:'200px', '300px': '250px'}" data-kt-drawer-direction="end" data-kt-drawer-toggle="#kt_header_menu_mobile_toggle" data-kt-swapper="true" data-kt-swapper-mode="prepend" data-kt-swapper-parent="{default: '#kt_body', lg: '#kt_header_nav'}">
                    <!--begin::Menu-->
                    <div class="menu menu-lg-rounded menu-column menu-lg-row menu-state-bg menu-title-gray-700 menu-state-title-primary menu-state-icon-primary menu-state-bullet-primary menu-arrow-gray-400 fw-bold my-5 my-lg-0 align-items-stretch" id="#kt_header_menu" data-kt-menu="true">
                        <div class="menu-item me-lg-1">
                            <a class="menu-link active py-3" href="{{url("/")}}">
                                <span class="menu-title">Dashboard</span>
                            </a>
                        </div>
                    </div>
                    <!--end::Menu-->
                </div>
                <!--end::Menu wrapper-->
            </div>
            <!--end::Navbar-->
            <!--begin::Topbar-->
            <div class="d-flex align-items-stretch flex-shrink-0">
                <!--begin::Toolbar wrapper-->
                <div class="topbar d-flex align-items-stretch flex-shrink-0">
{{--                    <!--begin::Search-->--}}
{{--                    <div class="d-flex align-items-stretch">--}}
{{--                        <!--begin::Search-->--}}
{{--                        <div id="kt_header_search" class="d-flex align-items-stretch" data-kt-search-keypress="true"--}}
{{--                             data-kt-search-min-length="2"--}}
{{--                             data-kt-search-enter="enter"--}}
{{--                             data-kt-search-layout="menu"--}}
{{--                             data-kt-menu-trigger="auto"--}}
{{--                             data-kt-menu-overflow="false"--}}
{{--                             data-kt-menu-permanent="true"--}}
{{--                             data-kt-menu-placement="bottom-end"--}}
{{--                             data-kt-menu-flip="bottom">--}}
{{--                            <!--begin::Search toggle-->--}}
{{--                            <div class="d-flex align-items-stretch" data-kt-search-element="toggle" id="kt_header_search_toggle">--}}
{{--                                <div class="topbar-item px-3 px-lg-5">--}}
{{--                                    <i class="bi bi-search fs-3"></i>--}}
{{--                                </div>--}}
{{--                            </div>--}}
{{--                            <!--end::Search toggle-->--}}
{{--                        </div>--}}
{{--                        <!--end::Search-->--}}
{{--                    </div>--}}
{{--                    <!--end::Search-->--}}

{{--                    <!--begin::Chat-->--}}
{{--                    <div class="d-flex align-items-stretch">--}}
{{--                        <!--begin::Menu wrapper-->--}}
{{--                        <div class="topbar-item position-relative px-3 px-lg-5" id="kt_drawer_chat_toggle">--}}
{{--                            <i class="bi bi-chat-left-text fs-3"></i>--}}
{{--                            <span class="bullet bullet-dot bg-success h-6px w-6px position-absolute translate-middle top-0 mt-4 start-50 animation-blink"></span>--}}
{{--                        </div>--}}
{{--                        <!--end::Menu wrapper-->--}}
{{--                    </div>--}}
{{--                    <!--end::Chat-->--}}
                    <!--begin::User-->
                    <div class="d-flex align-items-stretch" id="kt_header_user_menu_toggle">
                        <!--begin::Menu wrapper-->
                        <div class="topbar-item cursor-pointer symbol px-3 px-lg-5 me-n3 me-lg-n5 symbol-30px symbol-md-35px" data-kt-menu-trigger="click" data-kt-menu-attach="parent" data-kt-menu-placement="bottom-end" data-kt-menu-flip="bottom">
                            <img src="{{asset("assets/media/logos/isuzu.jpg")}}" alt="TG3" />
                        </div>
                        <!--begin::Menu-->
                        <div class="menu menu-sub menu-sub-dropdown menu-column menu-rounded menu-gray-800 menu-state-bg menu-state-primary fw-bold py-4 fs-6 w-275px" data-kt-menu="true">
                            <!--begin::Menu item-->
                            <div class="menu-item px-3">
                                <div class="menu-content d-flex align-items-center px-3">
                                    <!--begin::Avatar-->
                                    <div class="symbol symbol-50px me-5">
                                        <span style="color: dimgrey; font-weight: bold; font-size: 20px;">TG<span style="color: red; font-weight: bold"> 3</span></span>
                                    </div>
                                    <!--end::Avatar-->
                                    <!--begin::Username-->
                                    <div class="d-flex flex-column">
                                        <div class="fw-bolder d-flex align-items-center fs-5">TG3
                                        <span class="badge badge-light-success fw-bolder fs-8 px-2 py-1 ms-2">Pro</span></div>
                                        <a href="#" class="fw-bold text-muted text-hover-primary fs-7">tg3@lixnet.net</a>
                                    </div>
                                    <!--end::Username-->
                                </div>
                            </div>
                            <!--end::Menu item-->
                            <!--begin::Menu separator-->
                            <div class="separator my-2"></div>
                            <!--end::Menu separator-->

                            <!--begin::Menu item-->
                            <div class="menu-item px-5 my-1">
                                <a href="{{route('client.settings')}}" class="menu-link px-5">Account Settings</a>
                            </div>
                            <!--end::Menu item-->
                            <!--begin::Menu separator-->
                            <div class="separator my-2"></div>
                            <!--end::Menu separator-->
                            <!--begin::Menu item-->
                            <div class="menu-item px-5">
                                <a href="{{route('exit')}}" class="menu-link px-5">Sign Out</a>
                            </div>
                            <!--end::Menu item-->
                        </div>
                        <!--end::Menu-->
                        <!--end::Menu wrapper-->
                    </div>
                    <!--end::User -->
                    <!--begin::Heaeder menu toggle-->
                    <div class="d-flex align-items-stretch d-lg-none px-3 me-n3" title="Show header menu">
                        <div class="topbar-item" id="kt_header_menu_mobile_toggle">
                            <i class="bi bi-text-left fs-1"></i>
                        </div>
                    </div>
                    <!--end::Heaeder menu toggle-->
                </div>
                <!--end::Toolbar wrapper-->
            </div>
            <!--end::Topbar-->
        </div>
        <!--end::Wrapper-->
    </div>
    <!--end::Container-->
</div>
<!--end::Header-->

resources/views/layouts/index.blade.php
<!DOCTYPE html>
<html lang="{{app()->getLocale()}}">
<head>
		<title>TG3 Lixnet</title>
		<meta charset="utf-8" />
		<meta name="description" content="The Fastest Growing Sofware Company in Eastern Africa" />
		<meta name="keywords" content="Lixnet, Whatsapp Bot, Sofware Companies Kenya, Nairobi, CRM, CMS, HR, PAYROLL, ERP" />
		<meta name="viewport" content="width=device-width, initial-scale=1" />
		<meta property="og:locale" content="en_US" />
		<meta property="og:type" content="article" />
		<meta property="og:title" content="Lixnet - WhatsApp Bot" />
		<meta property="og:url" content="https://tg3.lixnet.net" />
		<meta property="og:site_name" content="Lixnet | WhatsApp Bot" />
        <meta name="csrf-token" content="{{ csrf_token() }}">

		<link rel="canonical" href="https://tg3.lixnet.net" />
		<link rel="shortcut icon" href="{{asset("assets/media/logos/favicon.ico")}}" />
		<!--begin::Fonts-->
		<link rel="stylesheet" href="https://fonts.googleapis.com/css?family=Poppins:300,400,500,600,700" />
		<!--end::Fonts-->
		<!--begin::Page Vendor Stylesheets(used by this page)-->
		<link href="{{asset("assets/plugins/custom/fullcalendar/fullcalendar.bundle.css")}}" rel="stylesheet" type="text/css" />
		<!--end::Page Vendor Stylesheets-->
		<!--begin::Global Stylesheets Bundle(used by all pages)-->
        <!--begin::Page Vendor Stylesheets(used by this page)-->
        <link href="{{asset("assets/plugins/custom/datatables/datatables.bundle.css")}}" rel="stylesheet" type="text/css" />
        <!--end::Page Vendor Stylesheets-->
        @stack('styles')
		<link href="{{asset("assets/plugins/global/plugins.bundle.css")}}" rel="stylesheet" type="text/css" />
		<link href="{{asset("assets/css/style.bundle.css")}}" rel="stylesheet" type="text/css" />
		<!--end::Global Stylesheets Bundle-->
	</head>
	<!--end::Head-->
	<!--begin::Body-->
	<body id="kt_body" class="header-fixed header-tablet-and-mobile-fixed toolbar-enabled toolbar-fixed toolbar-tablet-and-mobile-fixed aside-enabled aside-fixed"
    style="--kt-toolbar-height:55px;--kt-toolbar-height-tablet-and-mobile:55px">
		<!--begin::Main-->
		<!--begin::Root-->
		<div class="d-flex flex-column flex-root">
			<!--begin::Page-->
			<div class="page d-flex flex-row flex-column-fluid">
                @if (auth()->user()->role==1)
                  @include('layouts.sidebar')
                @else
                  @include('client.layouts.client_aside')
                @endif

				<!--begin::Wrapper-->
				<div class="wrapper d-flex flex-column flex-row-fluid" id="kt_wrapper">
					@include('layouts.header')
					    @yield('content')
					@include('layouts.footer')
                </div>
				<!--end::Wrapper-->
			</div>
			<!--end::Page-->
		</div>
		<!--end::Root-->
		<!--begin::Scrolltop-->
		<div id="kt_scrolltop" class="scrolltop" data-kt-scrolltop="true">
			<!--begin::Svg Icon | path: icons/duotune/arrows/arr066.svg-->
			<span class="svg-icon">
				<svg xmlns="http://www.w3.org/2000/svg" width="24" height="24" viewBox="0 0 24 24" fill="none">
					<rect opacity="0.5" x="13" y="6" width="13" height="2" rx="1" transform="rotate(90 13 6)" fill="black" />
					<path d="M12.5657 8.56569L16.75 12.75C17.1642 13.1642 17.8358 13.1642 18.25 12.75C18.6642 12.3358 18.6642 11.6642 18.25 11.25L12.7071 5.70711C12.3166 5.31658 11.6834 5.31658 11.2929 5.70711L5.75 11.25C5.33579 11.6642 5.33579 12.3358 5.75 12.75C6.16421 13.1642 6.83579 13.1642 7.25 12.75L11.4343 8.56569C11.7467 8.25327 12.2533 8.25327 12.5657 8.56569Z" fill="black" />
				</svg>
			</span>
			<!--end::Svg Icon-->
		</div>
		<!--end::Scrolltop-->
		<!--end::Main-->
		<script>var hostUrl = "{{url("/admin")}}";</script>
		<!--begin::Javascript-->
		<!--begin::Global Javascript Bundle(used by all pages)-->
		<script src="{{asset("assets/plugins/global/plugins.bundle.js")}}"></script>
		<script src="{{asset("assets/js/scripts.bundle.js")}}"></script>
		<!--end::Global Javascript Bundle-->
		<!--begin::Page Vendors Javascript(used by this page)-->
		<script src="{{asset("assets/plugins/custom/fullcalendar/fullcalendar.bundle.js")}}"></script>
		<!--end::Page Vendors Javascript-->
        <!--begin::Page Vendors Javascript(used by this page)-->
        <script src="{{asset("assets/plugins/custom/datatables/datatables.bundle.js")}}"></script>
        <!--end::Page Vendors Javascript-->
		<!--begin::Page Custom Javascript(used by this page)-->
        @stack('scripts')
        <script>
            @if(session('flash_message'))
             swal.fire("{{ session('flash_message') }}")
            @endif
        </script>
        <script src="{{asset("assets/plugins/custom/socketio/socket.io.js")}}"></script>
        <script src="{{asset("assets/plugins/custom/moment/moment.min.js")}}"></script>
		<script src="{{asset("assets/js/custom/widgets.js")}}"></script>
		<script src="{{asset("assets/js/custom/apps/chat/chat.js")}}"></script>
		<script src="{{asset("assets/js/custom/modals/create-app.js")}}"></script>
        <script src="{{asset("assets/js/custom/apps/user-management/users/list/table.js")}}"></script>
        <script src="{{asset("assets/js/custom/apps/file-manager/list.js")}}"></script>
		<script src="{{asset("assets/js/custom/modals/upgrade-plan.js")}}"></script>
		<script src="{{asset("assets/js/custom/intro.js")}}"></script>
		<!--end::Page Custom Javascript-->
		<!--end::Javascript-->
	</body>
	<!--end::Body-->
</html>